### PR TITLE
Restore Java worker

### PR DESCRIPTION
**Pull request by aanand**

### CODE REVIEW

**Comment by bfirsh** [comment]
How come? Is this because the .NET worker is unstable? Is it possible to fix that instead?

**Comment by thaJeztah** [comment]
ping @bfirsh looks like this .Net image is now replaced with a _Windows_ image, so think this may be needed (or changed to dotnetcore) https://twitter.com/jangelfdez/status/782280903053705217

**Comment by bfirsh** [comment]
I think it doesn't break because we use a specific tag. But agreed we should fix this properly at some point. It'd be nice to keep the .NET worker if we can...

**Comment by thaJeztah** [comment]
Yes, agreed, perhaps just changing the dotnet image to its new name would be good

**Comment by ManoMarks** [comment]
@aanand @bfirsh @thaJeztah What's the direction for this pull request? I'd prefer to keep the .NET work According to: https://hub.docker.com/r/microsoft/dotnet/ it does use a Linux base container unless you specify a nanoserver tag.
`FROM microsoft/dotnet`

**Comment by thaJeztah** [comment]
Isn't this their new home? https://hub.docker.com/r/microsoft/aspnetcore/ or is that a different image?

**Comment by ManoMarks** [comment]
I think it's a different image based on https://hub.docker.com/r/microsoft/dotnet/

**Comment by ManoMarks** [comment]
OK, after consulting with MS looks like the right version is microsoft/dotnet:1.0.0-preview2-sdk. I'm thinking maybe we maintain both code bases. Default to .NET or Java, but have a compose file that has the other. Thoughts?

**Pull request merged**
