### PR TITLE
Implement worker as a .NET Core app

### PR DESCRIPTION
**Pull request by natemcmaster**
This replaces the Java worker with a .NET Core implementation using the [RC2/Preview 1](https://github.com/dotnet/dotnet-docker/blob/master/1.0.0-preview1/Dockerfile) image. 

cc @SteveLasker @HaishiBai @Eilon @glennc

### CODE REVIEW

**Comment by Eilon** [comment]
My Java is a bit rusty, but the C# looks :shipit: to me.

**Comment by SteveLasker** [comment]
Yeah, Nate did a great job keeping the code concise. We're working on a proposal to clean up the dockerfile to have a more optimized image.

**Comment by friism** [comment]
@natemcmaster to reduce the final image size, instead of the default base image, I think you can get away with this:

```
FROM debian

# Work around https://github.com/dotnet/cli/issues/1582 until Docker releases a
# fix (https://github.com/docker/docker/issues/20818). This workaround allows
# the container to be run with the default seccomp Docker settings by avoiding
# the restart_syscall made by LTTng which causes a failed assertion.
ENV LTTNG_UST_REGISTER_TIMEOUT 0

# Install .NET CLI dependencies
RUN apt-get update \
     && apt-get install -y --no-install-recommends \
#         clang-3.5 \
#         libc6 \
         libcurl3 \
#         libgcc1 \
         libicu52 \
#         liblttng-ust0 \
         libssl1.0.0 \
#         libstdc++6 \
#         libtinfo5 \
         libunwind8 \
#         libuuid1 \
#         zlib1g \
     && rm -rf /var/lib/apt/lists/*

# Install .NET Core SDK
ENV DOTNET_CORE_SDK_VERSION 1.0.0-preview1-002702
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl\
    && curl -SL https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/$DOTNET_CORE_SDK_VERSION/dotnet-dev-debian-x64.$DOTNET_CORE_SDK_VERSION.tar.gz --output dotnet.tar.gz \
    && apt-get purge -y --auto-remove curl \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
```

@MichaelSimons

**Comment by friism** [comment]
@natemcmaster @SteveLasker so you'd have the above and then do what you're already doing in the same dockerfile

```
WORKDIR /app

ADD src/ /app/src/

RUN dotnet restore -v minimal src/ \
    && dotnet publish -c Release -o ./ src/Worker/ \
    && rm -rf src/ $HOME/.nuget/

CMD dotnet Worker.dll
```

the resulting image size is not too bad

**Comment by friism** [comment]
@bfirsh I've tested that this works end-to-end

**Comment by friism** [comment]
Full Dockerfile

```
FROM debian

# Work around https://github.com/dotnet/cli/issues/1582 until Docker releases a
# fix (https://github.com/docker/docker/issues/20818). This workaround allows
# the container to be run with the default seccomp Docker settings by avoiding
# the restart_syscall made by LTTng which causes a failed assertion.
ENV LTTNG_UST_REGISTER_TIMEOUT 0

# Install .NET CLI dependencies
RUN apt-get update \
     && apt-get install -y --no-install-recommends \
         ca-certificates \
         curl \
         libcurl3 \
         libicu52 \
         libssl1.0.0 \
         libunwind8 \
     && rm -rf /var/lib/apt/lists/*

# Install .NET Core SDK
ENV DOTNET_CORE_SDK_VERSION 1.0.0-preview1-002702
RUN apt-get update \
    && curl -SL https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/$DOTNET_CORE_SDK_VERSION/dotnet-dev-debian-x64.$DOTNET_CORE_SDK_VERSION.tar.gz --output dotnet.tar.gz \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

WORKDIR /app

ADD src/ /app/src/

RUN dotnet restore -v minimal src/ \
    && dotnet publish -c Release -o ./ src/Worker/ \
    && rm -rf src/ $HOME/.nuget/

CMD dotnet Worker.dll
```

**Comment by bfirsh** [comment]
LGTM

**Comment by bfirsh** [comment]
@friism I quite like the neatness of the smaller Dockerfile. What's the diff in image size? Maybe we can do this in a follow-up PR for the sake of getting this moving.

**Comment by friism** [comment]
@bfirsh it's ~600MB

**Comment by SteveLasker** [comment]
The size is fairly important, at least until we get the build and run (fat/thin) containers worked out. Having an image half the size at ~300 mb is quite a difference.

**Comment by natemcmaster** [comment]
FWIW, we intend to create an Alpine-based version of the dotnet image for the next release. This should cut much of the fat that comes from the jessie base image. Cref https://github.com/dotnet/dotnet-docker/issues/22 cc @dleeapho

**Pull request merged**
