### PR TITLE
Add image defs

### PR DESCRIPTION
**Pull request by dhiltgen**
This should help make the example app more DAB friendly.

### CODE REVIEW

**Comment by bfirsh** [comment]
This won't work if you don't have access to the "docker" org, right? And if you do, it'll blow away the automated build, which is not desired behaviour.

@aanand @friism did we ever figure out a pattern here that actually works?

**Comment by friism** [comment]
Yeah, see https://github.com/docker/compose/issues/3639

**Comment by dhiltgen** [comment]
Hmm... I've followed some of those threads and I'm still not clear what the recommended best practice is on setting up a compose file for dab use...  Is there a more succinct write-up someplace?

**Comment by aanand** [comment]
I don't think we have a good workflow figured out. Brain dump in https://github.com/docker/compose/issues/3639#issuecomment-232150619.

Perhaps, for the time being, we should leave the `image` keys out, and recommend in the README that people who want to create bundles make a `docker-compose.override.yml` file with image locators to which they have write access. e.g.

```yaml
vote:
  image: myusername/voting-app-vote
worker:
  image: myusername/voting-app-worker
result:
  image: myusername/voting-app-result
```

**Pull request closed without merging**
